#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=24gb,walltime=0:15:00
#PBS -N app-temp-convert-or-visualizer

mkdir -p wmc

time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/main
